/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kocla' at '16-12-23 下午8:09' with Gradle 3.2.1
 *
 * @author kocla, @date 16-12-23 下午8:09
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
